# Generated by Django 5.1.4 on 2025-11-13 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0002_initial"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("position", models.IntegerField(default=0)),
                ("row_count", models.IntegerField(default=100)),
                ("column_count", models.IntegerField(default=26)),
                ("frozen_rows", models.IntegerField(default=0)),
                ("frozen_columns", models.IntegerField(default=0)),
                ("show_grid_lines", models.BooleanField(default=True)),
                ("show_row_headings", models.BooleanField(default=True)),
                ("show_column_headings", models.BooleanField(default=True)),
                ("is_protected", models.BooleanField(default=False)),
                ("protection_password", models.CharField(blank=True, max_length=128)),
                ("tab_color", models.CharField(default="#ffffff", max_length=7)),
                ("is_hidden", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Chart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("line", "Line"),
                            ("bar", "Bar"),
                            ("column", "Column"),
                            ("pie", "Pie"),
                            ("area", "Area"),
                            ("scatter", "Scatter"),
                            ("radar", "Radar"),
                            ("bubble", "Bubble"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data_range", models.JSONField()),
                ("config", models.JSONField(default=dict)),
                ("position", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charts",
                        to="spreadsheets.sheet",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Spreadsheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("is_template", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "permission_level",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("team", "Team"),
                            ("workspace", "Workspace"),
                            ("public", "Public"),
                        ],
                        default="team",
                        max_length=20,
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("view_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_spreadsheets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_edited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="last_edited_spreadsheets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spreadsheets",
                        to="projects.project",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spreadsheets",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="sheet",
            name="spreadsheet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sheets",
                to="spreadsheets.spreadsheet",
            ),
        ),
        migrations.CreateModel(
            name="SpreadsheetComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("row", models.IntegerField()),
                ("column", models.IntegerField()),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="spreadsheets.spreadsheetcomment",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_spreadsheet_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="spreadsheets.sheet",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SpreadsheetEditor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("viewer", "Viewer"),
                            ("commenter", "Commenter"),
                            ("editor", "Editor"),
                            ("owner", "Owner"),
                        ],
                        max_length=20,
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("last_viewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "spreadsheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spreadsheets.spreadsheet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-added_at"],
                "unique_together": {("spreadsheet", "user")},
            },
        ),
        migrations.AddField(
            model_name="spreadsheet",
            name="editors",
            field=models.ManyToManyField(
                related_name="editable_spreadsheets",
                through="spreadsheets.SpreadsheetEditor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="SpreadsheetSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("selected_cell", models.JSONField(blank=True, null=True)),
                ("selected_range", models.JSONField(blank=True, null=True)),
                ("user_color", models.CharField(max_length=7)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity_at", models.DateTimeField(auto_now=True)),
                (
                    "active_sheet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="spreadsheets.sheet",
                    ),
                ),
                (
                    "spreadsheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_sessions",
                        to="spreadsheets.spreadsheet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_activity_at"],
            },
        ),
        migrations.CreateModel(
            name="SpreadsheetOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("cell_update", "Cell Update"),
                            ("row_insert", "Row Insert"),
                            ("row_delete", "Row Delete"),
                            ("column_insert", "Column Insert"),
                            ("column_delete", "Column Delete"),
                            ("format_update", "Format Update"),
                            ("merge_cells", "Merge Cells"),
                            ("unmerge_cells", "Unmerge Cells"),
                        ],
                        max_length=20,
                    ),
                ),
                ("operation_data", models.JSONField()),
                ("base_version", models.IntegerField()),
                ("sequence_number", models.IntegerField()),
                ("is_acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "spreadsheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="spreadsheets.spreadsheet",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="spreadsheets.spreadsheetsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "sequence_number"],
            },
        ),
        migrations.CreateModel(
            name="Cell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row", models.IntegerField()),
                ("column", models.IntegerField()),
                ("value", models.TextField(blank=True)),
                ("formula", models.TextField(blank=True)),
                ("computed_value", models.TextField(blank=True)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("boolean", "Boolean"),
                            ("date", "Date"),
                            ("time", "Time"),
                            ("datetime", "DateTime"),
                            ("currency", "Currency"),
                            ("percentage", "Percentage"),
                            ("formula", "Formula"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("format_config", models.JSONField(default=dict)),
                ("validation_config", models.JSONField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("hyperlink", models.URLField(blank=True)),
                ("merge_config", models.JSONField(blank=True, null=True)),
                ("is_locked", models.BooleanField(default=False)),
                ("version", models.IntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_cells",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cells",
                        to="spreadsheets.sheet",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["sheet", "row", "column"],
                        name="spreadsheet_sheet_i_431a88_idx",
                    ),
                    models.Index(
                        fields=["sheet", "updated_at"],
                        name="spreadsheet_sheet_i_ec3242_idx",
                    ),
                ],
                "unique_together": {("sheet", "row", "column")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="sheet",
            unique_together={("spreadsheet", "name")},
        ),
        migrations.CreateModel(
            name="NamedRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_row", models.IntegerField()),
                ("start_column", models.IntegerField()),
                ("end_row", models.IntegerField()),
                ("end_column", models.IntegerField()),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spreadsheets.sheet",
                    ),
                ),
                (
                    "spreadsheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="named_ranges",
                        to="spreadsheets.spreadsheet",
                    ),
                ),
            ],
            options={
                "unique_together": {("spreadsheet", "name")},
            },
        ),
        migrations.AddIndex(
            model_name="spreadsheet",
            index=models.Index(
                fields=["workspace", "is_archived"],
                name="spreadsheet_workspa_8d6f8d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="spreadsheet",
            index=models.Index(
                fields=["created_by", "updated_at"],
                name="spreadsheet_created_0c4c70_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="spreadsheetsession",
            index=models.Index(
                fields=["spreadsheet", "is_active"],
                name="spreadsheet_spreads_518b19_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="spreadsheetoperation",
            index=models.Index(
                fields=["spreadsheet", "created_at"],
                name="spreadsheet_spreads_a7e278_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="spreadsheetoperation",
            index=models.Index(
                fields=["session", "sequence_number"],
                name="spreadsheet_session_36f2b4_idx",
            ),
        ),
    ]
