# Generated by Django 5.2.8 on 2025-11-13 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Workspace name", max_length=100)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly workspace identifier",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Workspace description",
                        max_length=500,
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to workspace logo",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Workspace is active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Workspace creation timestamp",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last update timestamp"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Workspace owner",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_workspaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Workspace",
                "verbose_name_plural": "Workspaces",
                "db_table": "workspaces",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("member", "Member"),
                            ("guest", "Guest"),
                        ],
                        default="member",
                        help_text="Member role (display only)",
                        max_length=20,
                    ),
                ),
                (
                    "permissions",
                    models.BigIntegerField(
                        default=0,
                        help_text="Bitmap for workspace permissions (64 bits)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Membership is active"
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Member joined timestamp",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last update timestamp"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Member user",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        help_text="Associated workspace",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workspace Member",
                "verbose_name_plural": "Workspace Members",
                "db_table": "workspace_members",
                "ordering": ["-joined_at"],
            },
        ),
        migrations.AddIndex(
            model_name="workspace",
            index=models.Index(fields=["slug"], name="workspaces_slug_cac896_idx"),
        ),
        migrations.AddIndex(
            model_name="workspace",
            index=models.Index(
                fields=["owner", "is_active"], name="workspaces_owner_i_a912d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspace",
            index=models.Index(
                fields=["created_at"], name="workspaces_created_05cfe1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspacemember",
            index=models.Index(
                fields=["workspace", "user"], name="workspace_m_workspa_7679d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspacemember",
            index=models.Index(
                fields=["workspace", "is_active"], name="workspace_m_workspa_17e6ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspacemember",
            index=models.Index(
                fields=["user", "is_active"], name="workspace_m_user_id_96246a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspacemember",
            index=models.Index(
                fields=["joined_at"], name="workspace_m_joined__a03d93_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workspacemember",
            unique_together={("workspace", "user")},
        ),
    ]
