"""
AI Models
Track AI interactions and generated content
"""

from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from users.models import User
from workspaces.models import Workspace


class AIInteraction(models.Model):
    """Track AI interactions and usage."""

    INTERACTION_TYPES = [
        ('completion', 'Text Completion'),
        ('suggestion', 'Smart Suggestion'),
        ('summary', 'Content Summary'),
        ('translation', 'Translation'),
        ('code_review', 'Code Review'),
        ('chat', 'Chat Conversation'),
        ('analysis', 'Content Analysis'),
    ]

    workspace = models.ForeignKey(Workspace, on_delete=models.CASCADE, related_name='ai_interactions')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    interaction_type = models.CharField(max_length=50, choices=INTERACTION_TYPES)

    # Generic relation to any object (document, issue, etc.)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, null=True, blank=True)
    object_id = models.PositiveIntegerField(null=True, blank=True)
    content_object = GenericForeignKey('content_type', 'object_id')

    # Interaction data
    prompt = models.TextField()
    response = models.TextField()
    model_used = models.CharField(max_length=100, default='gemini-pro')

    # Metadata
    tokens_used = models.IntegerField(default=0)
    duration_ms = models.IntegerField(default=0)
    temperature = models.FloatField(default=0.7)
    max_tokens = models.IntegerField(null=True, blank=True)

    # Context
    context_data = models.JSONField(default=dict, blank=True)

    # User feedback
    rating = models.IntegerField(null=True, blank=True)  # 1-5 stars
    feedback = models.TextField(blank=True)

    created_at = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['workspace', 'user', '-created_at']),
            models.Index(fields=['interaction_type', '-created_at']),
        ]

    def __str__(self):
        return f"{self.interaction_type} - {self.user.email}"


class AISmartSuggestion(models.Model):
    """Smart suggestions generated by AI."""

    SUGGESTION_TYPES = [
        ('task', 'Task Suggestion'),
        ('reply', 'Reply Suggestion'),
        ('tag', 'Tag Suggestion'),
        ('assignment', 'Assignment Suggestion'),
        ('priority', 'Priority Suggestion'),
        ('deadline', 'Deadline Suggestion'),
    ]

    workspace = models.ForeignKey(Workspace, on_delete=models.CASCADE, related_name='ai_suggestions')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    suggestion_type = models.CharField(max_length=50, choices=SUGGESTION_TYPES)

    # Generic relation to any object
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, null=True, blank=True)
    object_id = models.PositiveIntegerField(null=True, blank=True)
    content_object = GenericForeignKey('content_type', 'object_id')

    # Suggestion data
    suggestion = models.TextField()
    confidence_score = models.FloatField(default=0.0)  # 0.0 to 1.0
    reasoning = models.TextField(blank=True)

    # Status
    status = models.CharField(
        max_length=20,
        choices=[
            ('pending', 'Pending'),
            ('accepted', 'Accepted'),
            ('rejected', 'Rejected'),
            ('dismissed', 'Dismissed'),
        ],
        default='pending'
    )

    accepted_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['workspace', 'status', '-created_at']),
        ]

    def __str__(self):
        return f"{self.suggestion_type} - {self.suggestion[:50]}"


class AIModelConfig(models.Model):
    """AI model configuration per workspace."""

    workspace = models.ForeignKey(Workspace, on_delete=models.CASCADE, related_name='ai_configs')

    # Model settings
    model_name = models.CharField(max_length=100, default='gemini-pro')
    api_key = models.CharField(max_length=500, blank=True)  # Encrypted in production

    # Default parameters
    default_temperature = models.FloatField(default=0.7)
    default_max_tokens = models.IntegerField(default=1000)
    default_top_p = models.FloatField(default=0.9)
    default_top_k = models.IntegerField(default=40)

    # Usage limits
    daily_request_limit = models.IntegerField(default=1000)
    monthly_token_limit = models.IntegerField(default=100000)

    # Current usage
    requests_today = models.IntegerField(default=0)
    tokens_this_month = models.IntegerField(default=0)
    last_reset_date = models.DateField(auto_now_add=True)

    # Features enabled
    enable_completions = models.BooleanField(default=True)
    enable_suggestions = models.BooleanField(default=True)
    enable_summaries = models.BooleanField(default=True)
    enable_translations = models.BooleanField(default=True)
    enable_code_review = models.BooleanField(default=True)

    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ['workspace']

    def __str__(self):
        return f"AI Config for {self.workspace.name}"
