# Generated by Django 5.2.8 on 2025-11-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        db_index=True,
                        help_text="Issue identifier (e.g., PROJ-123)",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(help_text="Issue title", max_length=300)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Issue description (supports markdown)",
                    ),
                ),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("task", "Task"),
                            ("bug", "Bug"),
                            ("feature", "Feature"),
                            ("improvement", "Improvement"),
                        ],
                        default="task",
                        help_text="Issue type",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("no_priority", "No Priority"),
                            ("urgent", "Urgent"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        db_index=True,
                        default="no_priority",
                        help_text="Issue priority",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("backlog", "Backlog"),
                            ("todo", "To Do"),
                            ("in_progress", "In Progress"),
                            ("in_review", "In Review"),
                            ("done", "Done"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="backlog",
                        help_text="Issue status",
                        max_length=20,
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, help_text="Display order within status column"
                    ),
                ),
                (
                    "estimate",
                    models.IntegerField(
                        blank=True, help_text="Time estimate in hours", null=True
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, help_text="Issue due date", null=True),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="Issue started timestamp", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="Issue completed timestamp", null=True
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, help_text="Issue cancelled timestamp", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Issue creation timestamp",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last update timestamp"
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue",
                "verbose_name_plural": "Issues",
                "db_table": "issues",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IssueAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(help_text="Original file name", max_length=255),
                ),
                (
                    "file_url",
                    models.URLField(
                        help_text="URL to file (S3/storage)", max_length=1000
                    ),
                ),
                ("file_size", models.IntegerField(help_text="File size in bytes")),
                (
                    "file_type",
                    models.CharField(help_text="File MIME type", max_length=100),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Upload timestamp"
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue Attachment",
                "verbose_name_plural": "Issue Attachments",
                "db_table": "issue_attachments",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="IssueComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Comment content (supports markdown)"),
                ),
                (
                    "is_edited",
                    models.BooleanField(
                        default=False, help_text="Comment has been edited"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Comment creation timestamp",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last update timestamp"
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue Comment",
                "verbose_name_plural": "Issue Comments",
                "db_table": "issue_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Label name", max_length=50)),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Label description",
                        max_length=200,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#10B981", help_text="Label color (hex)", max_length=7
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Label creation timestamp"
                    ),
                ),
            ],
            options={
                "verbose_name": "Label",
                "verbose_name_plural": "Labels",
                "db_table": "labels",
                "ordering": ["name"],
            },
        ),
    ]
