# Generated by Django 5.2.8 on 2025-11-13 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("issues", "0001_initial"),
        ("projects", "0001_initial"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                help_text="Assigned user",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_issues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent issue",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_issues",
                to="issues.issue",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="project",
            field=models.ForeignKey(
                help_text="Associated project",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="reporter",
            field=models.ForeignKey(
                help_text="Issue reporter",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reported_issues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="workspace",
            field=models.ForeignKey(
                help_text="Associated workspace",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="issueattachment",
            name="issue",
            field=models.ForeignKey(
                help_text="Associated issue",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="issues.issue",
            ),
        ),
        migrations.AddField(
            model_name="issueattachment",
            name="uploaded_by",
            field=models.ForeignKey(
                help_text="User who uploaded",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issue_attachments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issuecomment",
            name="author",
            field=models.ForeignKey(
                help_text="Comment author",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issue_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="issuecomment",
            name="issue",
            field=models.ForeignKey(
                help_text="Associated issue",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="issues.issue",
            ),
        ),
        migrations.AddField(
            model_name="label",
            name="workspace",
            field=models.ForeignKey(
                help_text="Associated workspace",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="labels",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="labels",
            field=models.ManyToManyField(
                blank=True,
                help_text="Issue labels",
                related_name="issues",
                to="issues.label",
            ),
        ),
        migrations.AddIndex(
            model_name="issueattachment",
            index=models.Index(fields=["issue"], name="issue_attac_issue_i_4e0c70_idx"),
        ),
        migrations.AddIndex(
            model_name="issueattachment",
            index=models.Index(
                fields=["uploaded_by"], name="issue_attac_uploade_64d3f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issuecomment",
            index=models.Index(
                fields=["issue", "created_at"], name="issue_comme_issue_i_937053_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issuecomment",
            index=models.Index(
                fields=["author"], name="issue_comme_author__1cd3cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="label",
            index=models.Index(
                fields=["workspace", "name"], name="labels_workspa_d7b2e7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="label",
            unique_together={("workspace", "name")},
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["workspace", "status"], name="issues_workspa_882993_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["project", "status"], name="issues_project_6804e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["assignee", "status"], name="issues_assigne_2da979_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["identifier"], name="issues_identif_cf128e_idx"),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["priority", "status"], name="issues_priorit_2b5670_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["created_at"], name="issues_created_febe30_idx"),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["status", "sort_order"], name="issues_status_88a048_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="issue",
            unique_together={("workspace", "identifier")},
        ),
    ]
