# Generated by Django 5.2.8 on 2025-11-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Channel name", max_length=100)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly channel identifier", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Channel description",
                        max_length=500,
                    ),
                ),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("direct", "Direct Message"),
                        ],
                        db_index=True,
                        default="public",
                        help_text="Channel type",
                        max_length=20,
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        db_index=True, default=False, help_text="Channel is archived"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Channel creation timestamp",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last update timestamp"
                    ),
                ),
            ],
            options={
                "verbose_name": "Channel",
                "verbose_name_plural": "Channels",
                "db_table": "channels",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ChannelMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mute_notifications",
                    models.BooleanField(
                        default=False, help_text="Mute channel notifications"
                    ),
                ),
                (
                    "last_read_at",
                    models.DateTimeField(
                        blank=True, help_text="Last time user read messages", null=True
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Member joined timestamp"
                    ),
                ),
            ],
            options={
                "verbose_name": "Channel Member",
                "verbose_name_plural": "Channel Members",
                "db_table": "channel_members",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Message content (supports markdown)"),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("system", "System"),
                            ("attachment", "Attachment"),
                        ],
                        default="text",
                        help_text="Message type",
                        max_length=20,
                    ),
                ),
                (
                    "thread_reply_count",
                    models.IntegerField(
                        default=0, help_text="Number of thread replies"
                    ),
                ),
                (
                    "mentions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="User IDs mentioned in message",
                    ),
                ),
                (
                    "is_edited",
                    models.BooleanField(
                        default=False, help_text="Message has been edited"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="Message is deleted"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Message creation timestamp",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last update timestamp"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Message deletion timestamp", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "db_table": "messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(help_text="Original file name", max_length=255),
                ),
                (
                    "file_url",
                    models.URLField(
                        help_text="URL to file (S3/storage)", max_length=1000
                    ),
                ),
                ("file_size", models.IntegerField(help_text="File size in bytes")),
                (
                    "file_type",
                    models.CharField(help_text="File MIME type", max_length=100),
                ),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True,
                        help_text="Thumbnail URL for images/videos",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Upload timestamp"
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Attachment",
                "verbose_name_plural": "Message Attachments",
                "db_table": "message_attachments",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emoji",
                    models.CharField(help_text="Emoji unicode or name", max_length=50),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Reaction creation timestamp"
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Reaction",
                "verbose_name_plural": "Message Reactions",
                "db_table": "message_reactions",
            },
        ),
    ]
