# Generated by Django 5.2.8 on 2025-11-13 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("messaging", "0001_initial"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="created_by",
            field=models.ForeignKey(
                help_text="Channel creator",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_channels",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="workspace",
            field=models.ForeignKey(
                help_text="Associated workspace",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channels",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="channelmember",
            name="channel",
            field=models.ForeignKey(
                help_text="Associated channel",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_members",
                to="messaging.channel",
            ),
        ),
        migrations.AddField(
            model_name="channelmember",
            name="user",
            field=models.ForeignKey(
                help_text="Member user",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="members",
            field=models.ManyToManyField(
                help_text="Channel members",
                related_name="channels",
                through="messaging.ChannelMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="author",
            field=models.ForeignKey(
                help_text="Message author",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="channel",
            field=models.ForeignKey(
                help_text="Associated channel",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="messaging.channel",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="parent_message",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent message for threaded replies",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thread_replies",
                to="messaging.message",
            ),
        ),
        migrations.AddField(
            model_name="messageattachment",
            name="message",
            field=models.ForeignKey(
                help_text="Associated message",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="messaging.message",
            ),
        ),
        migrations.AddField(
            model_name="messagereaction",
            name="message",
            field=models.ForeignKey(
                help_text="Associated message",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="messaging.message",
            ),
        ),
        migrations.AddField(
            model_name="messagereaction",
            name="user",
            field=models.ForeignKey(
                help_text="User who reacted",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_reactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="channelmember",
            index=models.Index(
                fields=["channel", "user"], name="channel_mem_channel_f82b52_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="channelmember",
            index=models.Index(fields=["user"], name="channel_mem_user_id_4d3616_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="channelmember",
            unique_together={("channel", "user")},
        ),
        migrations.AddIndex(
            model_name="channel",
            index=models.Index(
                fields=["workspace", "channel_type"], name="channels_workspa_f2b0ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="channel",
            index=models.Index(
                fields=["workspace", "is_archived"], name="channels_workspa_893f5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="channel",
            index=models.Index(fields=["slug"], name="channels_slug_8051e7_idx"),
        ),
        migrations.AddIndex(
            model_name="channel",
            index=models.Index(
                fields=["created_at"], name="channels_created_abf1b4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="channel",
            unique_together={("workspace", "slug")},
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["channel", "created_at"], name="messages_channel_68995e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["channel", "is_deleted", "created_at"],
                name="messages_channel_3697f2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["author"], name="messages_author__93b7f5_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["parent_message", "created_at"],
                name="messages_parent__0b80e6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["created_at"], name="messages_created_919c58_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messageattachment",
            index=models.Index(
                fields=["message"], name="message_att_message_2a1fa5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagereaction",
            index=models.Index(
                fields=["message"], name="message_rea_message_3fb393_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagereaction",
            index=models.Index(fields=["user"], name="message_rea_user_id_565363_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="messagereaction",
            unique_together={("message", "user", "emoji")},
        ),
    ]
