# Generated by Django 5.1.4 on 2025-11-13 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasskeyCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "credential_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique credential identifier (base64url encoded)",
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    "public_key",
                    models.TextField(help_text="Public key in PEM or COSE format"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='User-friendly name for the credential (e.g., "iPhone Touch ID")',
                        max_length=100,
                    ),
                ),
                (
                    "aaguid",
                    models.CharField(
                        blank=True,
                        help_text="Authenticator Attestation GUID",
                        max_length=100,
                    ),
                ),
                (
                    "authenticator_type",
                    models.CharField(
                        choices=[
                            ("platform", "Platform Authenticator"),
                            ("cross_platform", "Cross-Platform"),
                        ],
                        default="platform",
                        help_text="Type of authenticator device",
                        max_length=20,
                    ),
                ),
                (
                    "attestation_format",
                    models.CharField(
                        blank=True,
                        help_text="Attestation statement format (packed, fido-u2f, android-key, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "attestation_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Full attestation statement and data",
                    ),
                ),
                (
                    "sign_count",
                    models.BigIntegerField(
                        default=0,
                        help_text="Signature counter to detect cloned credentials",
                    ),
                ),
                (
                    "transports",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of supported transports (usb, nfc, ble, internal)",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this credential was used",
                        null=True,
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times this credential has been used",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Credential is active and can be used"
                    ),
                ),
                (
                    "is_backup_eligible",
                    models.BooleanField(
                        default=False,
                        help_text="Credential can be backed up and synced",
                    ),
                ),
                (
                    "is_backup_state",
                    models.BooleanField(
                        default=False, help_text="Credential is currently backed up"
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        help_text="Device name where credential was created",
                        max_length=200,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="User agent when credential was created"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address when credential was created",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Credential creation timestamp",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last update timestamp"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passkey_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Passkey Credential",
                "verbose_name_plural": "Passkey Credentials",
                "db_table": "passkey_credentials",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PasskeyAuthenticationAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("invalid_signature", "Invalid Signature"),
                            ("credential_not_found", "Credential Not Found"),
                            ("user_not_found", "User Not Found"),
                            ("rate_limited", "Rate Limited"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "challenge",
                    models.CharField(
                        help_text="Challenge used for this authentication attempt",
                        max_length=500,
                    ),
                ),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("country_code", models.CharField(blank=True, max_length=2)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("error_message", models.TextField(blank=True)),
                (
                    "attempted_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passkey_auth_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "credential",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auth_attempts",
                        to="users.passkeycredential",
                    ),
                ),
            ],
            options={
                "verbose_name": "Passkey Authentication Attempt",
                "verbose_name_plural": "Passkey Authentication Attempts",
                "db_table": "passkey_auth_attempts",
                "ordering": ["-attempted_at"],
            },
        ),
        migrations.CreateModel(
            name="PasskeyRegistrationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "challenge",
                    models.CharField(
                        help_text="Random challenge for this registration session",
                        max_length=500,
                        unique=True,
                    ),
                ),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Registration was successfully completed",
                    ),
                ),
                (
                    "is_expired",
                    models.BooleanField(default=False, help_text="Session has expired"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Session expiration time (typically 5 minutes)"
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passkey_registration_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Passkey Registration Session",
                "verbose_name_plural": "Passkey Registration Sessions",
                "db_table": "passkey_registration_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="passkeycredential",
            index=models.Index(
                fields=["user", "is_active"], name="passkey_cre_user_id_597035_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passkeycredential",
            index=models.Index(
                fields=["credential_id"], name="passkey_cre_credent_3e9af2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passkeycredential",
            index=models.Index(
                fields=["created_at"], name="passkey_cre_created_e11950_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passkeyauthenticationattempt",
            index=models.Index(
                fields=["user", "attempted_at"], name="passkey_aut_user_id_b8c8d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passkeyauthenticationattempt",
            index=models.Index(
                fields=["status", "attempted_at"], name="passkey_aut_status_69eba8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passkeyauthenticationattempt",
            index=models.Index(
                fields=["ip_address", "attempted_at"],
                name="passkey_aut_ip_addr_c9e6e6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="passkeyregistrationsession",
            index=models.Index(
                fields=["user", "is_completed"], name="passkey_reg_user_id_ae0719_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passkeyregistrationsession",
            index=models.Index(
                fields=["challenge"], name="passkey_reg_challen_a5aa7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passkeyregistrationsession",
            index=models.Index(
                fields=["expires_at"], name="passkey_reg_expires_bfe19d_idx"
            ),
        ),
    ]
